# train and val datasets (image directory or *.txt file with image paths)
train: /content/pytorch_custom_yolo_training-6/data/model-trains3/train.txt
val: /content/pytorch_custom_yolo_training-6/data/model-trains3/val.txt
test: /content/pytorch_custom_yolo_training-6/data/model-trains3/test.txt

# number of classes
nc: 8

# class names
names: ['Trolley', 'Locomotive', 'Passenger', 'Tanker', 'Hammer', 'Plyers', 'Cat', 'Screwdriver']