yolo_model:

  config_file:
    name: yolov3-3.cfg
  weight_file:
    name: yolov3.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - trolley
      - locomotive
      - passenger
      - tanker
      - hammer
      - plyers
      - cat
      - screwdriver