yolo_model:

  config_file:
    name: yolov3-2.cfg
  weight_file:
    name: yolov3.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - trolley
      - locomotive
      - passenger
      - tanker